DemoIdentity/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace FPTBook.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string? Name { get; set; }

        [Display(Name = "Category")]
        public int CategoryID { get; set; }
        public Category? Category { get; set; }

        public decimal Price { get; set; }

        [Display(Name = "Author")]
        public int AuthorID { get; set; }
        public Author? Author { get; set; }


        [Display(Name = "Publishing Company")]
        public int PublishingCompanyID { get; set; }
        public PublishingCompany? PublishingCompany { get; set; }


        public int Quantity { get; set; }
        public string? Description { get; set; }



        public string? ImgFileName { get; set; } // Thêm thuộc tính kiểu string để lưu trữ tên tệp hình ảnh

        public string? ImgFileExt { get; set; }
        // Thêm thuộc tính kiểu string để lưu trữ tên tệp hình ảnh

        public string FullPath { get { return $@"~/Images/{ImgFileName}"; } }
        // Thêm thuộc tính FullPath để lưu trữ đường dẫn đến hình ảnh sản phẩm

    }

    public class Author
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public ICollection<Book>? Books { get; set; }
    }
    public class Category
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public ICollection<Book>? Books { get; set; }
        public Category() { }
        public Category(TmpCategory tc)
        {
            this.Name = tc.Name;
        }
    }

    public class PublishingCompany
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public ICollection<Book>? Books { get; set; }
    }
}

DemoIdentity/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTBook.Models;
using FPTBookDemo.Data;
using Microsoft.AspNetCore.Authorization;

namespace FPTBook.Controllers
{
    [Authorize(Roles = "Owner")]
    public class AuthorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AuthorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index()
        {
              return _context.Author != null ? 
                          View(await _context.Author.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Author'  is null.");
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }

            var author = await _context.Author.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Author == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Author'  is null.");
            }
            var author = await _context.Author.FindAsync(id);
            if (author != null)
            {
                _context.Author.Remove(author);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
          return (_context.Author?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DemoIdentity/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTBook.Models;
using FPTBookDemo.Data;
using Microsoft.AspNetCore.Authorization;

namespace FPTBook.Controllers
{
    [Authorize(Roles = "Owner")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return _context.Category != null ? 
                          View(await _context.Category.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Category'  is null.");
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Category == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Category'  is null.");
            }
            var category = await _context.Category.FindAsync(id);
            if (category != null)
            {
                _context.Category.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Category?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DemoIdentity/Controllers/PublishingCompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTBook.Models;
using FPTBookDemo.Data;

namespace FPTBook.Controllers
{
    public class PublishingCompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PublishingCompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PublishingCompanies
        public async Task<IActionResult> Index()
        {
              return _context.PublishingCompany != null ? 
                          View(await _context.PublishingCompany.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.PublishingCompany'  is null.");
        }

        // GET: PublishingCompanies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PublishingCompany == null)
            {
                return NotFound();
            }

            var publishingCompany = await _context.PublishingCompany
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publishingCompany == null)
            {
                return NotFound();
            }

            return View(publishingCompany);
        }

        // GET: PublishingCompanies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PublishingCompanies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] PublishingCompany publishingCompany)
        {
            if (ModelState.IsValid)
            {
                _context.Add(publishingCompany);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(publishingCompany);
        }

        // GET: PublishingCompanies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PublishingCompany == null)
            {
                return NotFound();
            }

            var publishingCompany = await _context.PublishingCompany.FindAsync(id);
            if (publishingCompany == null)
            {
                return NotFound();
            }
            return View(publishingCompany);
        }

        // POST: PublishingCompanies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] PublishingCompany publishingCompany)
        {
            if (id != publishingCompany.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publishingCompany);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublishingCompanyExists(publishingCompany.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(publishingCompany);
        }

        // GET: PublishingCompanies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PublishingCompany == null)
            {
                return NotFound();
            }

            var publishingCompany = await _context.PublishingCompany
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publishingCompany == null)
            {
                return NotFound();
            }

            return View(publishingCompany);
        }

        // POST: PublishingCompanies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PublishingCompany == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PublishingCompany'  is null.");
            }
            var publishingCompany = await _context.PublishingCompany.FindAsync(id);
            if (publishingCompany != null)
            {
                _context.PublishingCompany.Remove(publishingCompany);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PublishingCompanyExists(int id)
        {
          return (_context.PublishingCompany?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DemoIdentity/Views/Books/Add2Cart.cshtml
@using FPTBook.Utils
@{
CartItem newItem=(CartItem)ViewData["newItem"];
}
<script language='javascript' type='text/javascript'>
alert('Adding [@newItem.Title] successful. Quantity= @newItem.Quantity!');
window.location.href='/Home'; //Đổi locaction tùy thích nhưng phù hợp
</script>

DemoIdentity/Views/Books/CheckOut.cshtml
@using FPTBook.Utils
@{
    List<CartItem> myItems = (List<CartItem>)ViewData["myItems"] ?? new List<CartItem>();
    decimal total = 0;

    if (myItems.Count == 0)
    {
        <h1>Your cart is empty</h1>
    }

    foreach (var item in myItems)
    {
        total += item.Price * item.Quantity;

        if (item.ID == null || item.Title == null || item.Price == null || item.Quantity == null)
        {
            <h1>There is an error in your cart</h1>
            break;
        }
    }
}

<table class="table table-striped">
    <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in myItems)
    {
        total += item.Price * item.Quantity;
        <tr>
            <form asp-action="EditOrder" method="post">
            <td>@item.Title</td>
            <td>@item.Price</td>
            <td><input type="number" min="0" name="quantity" value="@item.Quantity" /></td>
            <td>@(item.Price * item.Quantity)</td>
            <td>
                <input type="hidden" name="id" value="@item.ID" />
                <input type="submit" value="Update" class="btn btn-primary" />
            </td>
            </form>
            <td>
                <form asp-action="RemoveOrderItem" method="post">

                    <input type="hidden" name="id" value="@item.ID" />
                    <input type="submit" value="Remove" class="btn btn-danger" />
                </form>
        </tr>
    }
    <tr>
        <td colspan="3">Total:</td>
        <td>@total</td>
    </tr>
</table>
<form asp-action="PlaceOrder" method="post">
    <input type="hidden" name="total" value="@total" />
    <input type="submit" value="Order" class="btn btn-primary" />
</form>

DemoIdentity/Views/Books/Create.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <select asp-for="CategoryID" class ="form-control" asp-items="ViewBag.CategoryID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorID" class="control-label"></label>
                <select asp-for="AuthorID" class ="form-control" asp-items="ViewBag.AuthorID"></select>
            </div>
            <div class="form-group">
                <label asp-for="PublishingCompanyID" class="control-label"></label>
                <select asp-for="PublishingCompanyID" class ="form-control" asp-items="ViewBag.PublishingCompanyID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgFileName" class="control-label"></label>
                <input name="file" type="file" accept="image/*" />
                <span asp-validation-for="ImgFileName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoIdentity/Views/Books/Delete.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingCompany)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishingCompany.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImgFileName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImgFileName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImgFileExt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImgFileExt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoIdentity/Views/Books/Details.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="~/Image/@Model.ImgFileName" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-6">
                <div class="card">
                    <h4 class="card-title">@Model.Name</h4>
                    <p class="card-text">@Model.Description</p>
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Price)
                        </dt>
                        <dd class="col-sm-10">
                            @Model.Price
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Category)
                        </dt>
                        <dd class="col-sm-10">
                            @Model.Category.Name
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Author)
                        </dt>
                        <dd class="col-sm-10">
                            @Model.Author.Name
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.PublishingCompany)
                        </dt>
                        <dd class="col-sm-10">
                            @Model.PublishingCompany.Name
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Quantity)
                        </dt>
                        <dd class="col-sm-10">
                            @Model.Quantity
                        </dd>
                    </dl>
                </div>
        </div>
    </div>
</div>
<div>
    <script>
        $(document).ready(function() {
        if (User.IsInRole("User")) {
        $("#edit-button").hide();
        } else if (User.IsInRole("Owner")) {
        $("#edit-button").show();
        }
        });
    </script>
    @if (User.IsInRole("User"))
    {
            <form asp-action="Add2Cart" method="post">
                <input type="hidden" name="id" value="@Model.Id" />
                <input type="hidden" name="name" value="@Model.Name" />
                <input type="hidden" name="price" value="@Model.Price" />
                <input type="number" name="quantity" min="1" value="1" />
                <input type="submit" value="Add To Cart" class="btn btn-primary" />
            </form>

        <a asp-controller="Home" asp-action="Index">Back to Home</a>
    }
    else if (User.IsInRole("Owner"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
        <a asp-action="Index">Back to List</a>
    }    
@*     <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> | *@
    
</div>

DemoIdentity/Views/Books/Index.cshtml
@model IEnumerable<FPTBook.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-controller="Authors">Authors New</a>
    <a asp-controller="Categories">Categories New</a>
    <a asp-controller="PublishingCompanies">PublishingCompanies New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishingCompany)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImgFileName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Author.Name)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.PublishingCompany.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                    <img src="~/Image/@item.ImgFileName" alt="Image" style="width: 100px; high: 100px">
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>